FROM node:lts

RUN ln -s /usr/local/bin/node /usr/local/sbin/node

WORKDIR /application

COPY . .

RUN yarn config delete proxy
RUN yarn config delete https-proxy
RUN yarn install --production
RUN yarn build
RUN yarn install -g serve

ENV PATH /application/node_modules/.bin:$PATH

CMD ["serve", "-s", "build", "-l", "8114"]
