FROM node:16

RUN ln -s /usr/local/bin/node /usr/local/sbin/node

WORKDIR /application

COPY . .

RUN yarn config set script-shell $(which sh)
RUN yarn install --production --network-timeout 10000000
RUN yarn build
RUN yarn global add serve

ENV PATH /application/node_modules/.bin:$PATH

CMD ["serve", "-s", "build", "-l", "8114"]
