FROM node:lts-buster

RUN ln -s /usr/local/bin/node /usr/local/sbin/node

WORKDIR /application

COPY . .

RUN mkdir node_modules
RUN npm ci --omit=dev
RUN npm run build
RUN npm install -g serve

ENV PATH /application/node_modules/.bin:$PATH

CMD ["serve", "-s", "build", "-l", "8114"]
